modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"
[[mods]]
modId="acedium"
version="${version}"
displayName="Acedium Sodiumized"
displayTest = "IGNORE_SERVER_VERSION"
logoFile="assets/acedium/acedium-logo.png"
authors="Cortex, Ferri_Arnus, viktorr245"
description='''
Unofficial continuation of Acedium, a NeoForge port of Nvidium, updated for Sodium 0.8 on NeoForge 1.21.1.
'''

[modproperties.acedium]
"sodium:config_api_user" = "me.cortex.nvidium.config.ConfigGuiBuilder"

[[dependencies.acedium]]
modId = "neoforge"
type="required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acedium]]
modId = "minecraft"
type="required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.acedium]]
modId="sodium"
type="required"
versionRange="[0.8.12-beta.1,0.9)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "nvidium.mixins.json"
